const races = [
  {
    race: "GP da Austrália",
    date: "19 de Março",
    url: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_771/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Australia_Circuit",
    primeiraEdicao: "1996",
    tempoRecorde: "1:19.813 (Charles Leclerc (2024)",
    maiorVencedor: "Michael Schumacher (4 vitórias)",
    comprimento: "5.303 km",
    numVoltas: 58,
  },

  {
    race: "GP da China",
    date: "23 de Março",
    url: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/China_Circuit",
    primeiraEdicao: "2004",
    tempoRecorde: "1:32.238 (Michael Schumacher (2004)",
    maiorVencedor: "Lewis Hamilton (6 vitórias)",
    comprimento: "5.451 km",
    numVoltas: 56,
  },

  {
    race: "GP da Japão",
    date: "6 de Abril",
    url: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Japan_Circuit",
    primeiraEdicao: "1987",
    tempoRecorde: "1:30.965 (Kimi Antonelli (2025)",
    maiorVencedor: "Michael Schumacher (6 vitórias)",
    comprimento: "5.807 km",
    numVoltas: 53,
  },

  {
    race: "GP do Bahrein",
    date: "13 de Abril",
    url: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Bahrain_Circuit",
    primeiraEdicao: "2004",
    tempoRecorde: "1:31.447 (Pedro de la Rosa (2005)",
    maiorVencedor: "Lewis Hamilton (5 vitórias)",
    comprimento: "5.412 km",
    numVoltas: 57,
  },

  {
    race: "GP da Arábia Saudita",
    date: "20 de Abril",
    url: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Saudi_Arabia_Circuit",
    primeiraEdicao: "2021",
    tempoRecorde: "1:30.734 (Lewis Hamilton (2021)",
    maiorVencedor: "Max Verstappen (2 vitórias)",
    comprimento: "6.174 km",
    numVoltas: 50,
  },

  {
    race: "GP de Miami",
    date: "4 de Maio",
    url: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Miami_Circuit",
    primeiraEdicao: "2022",
    tempoRecorde: "1:29.708 (Max Verstappen (2023)",
    maiorVencedor: "Max Verstappen (2 vitórias)",
    comprimento: "5.412 km",
    numVoltas: 57,
  },

  {
    race: "GP da Emília-Romanha",
    date: "18 de Maio",
    url: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Emilia_Romagna_Circuit",
    primeiraEdicao: "1980",
    tempoRecorde: "1:15.484 (Lewis Hamilton (2020)",
    maiorVencedor:
      "Michael Schumacher (7 vitórias), na pista atual Max Verstappen (3 vitórias)",
    comprimento: "4.909 km",
    numVoltas: 63,
  },

  {
    race: "GP de Mônaco",
    date: "25 de Maio",
    url: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Monaco_Circuit",
    primeiraEdicao: "1950",
    tempoRecorde: "1:12.909 (Lewis Hamilton (2021)",
    maiorVencedor: "Ayrton Senna (6 vitórias)",
    comprimento: "3.337km",
    numVoltas: 58,
  },

  {
    race: "GP da Espanha",
    date: "1 de Junho",
    url: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Spain_Circuit",
    primeiraEdicao: "1991",
    tempoRecorde: "1:16.330 (Max Verstappen (2023)",
    maiorVencedor: "Michael Schumacher e Lewis Hamilton (6 vitórias)",
    comprimento: "4.657 km",
    numVoltas: 66,
  },

  {
    race: "GP do Canadá",
    date: "15 de Junho",
    url: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Canada_Circuit",
    primeiraEdicao: "1978",
    tempoRecorde: "1:13.078 (Valtteri Bottas (2019)",
    maiorVencedor: "Michael Schumacher e Lewis Hamilton (7 vitórias)",
    comprimento: "4.361 km",
    numVoltas: 70,
  },

  {
    race: "GP da Áustria ",
    date: "29 de Junho",
    url: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Austria_Circuit",
    primeiraEdicao: "1970",
    tempoRecorde: "1:05.619 (Carlos Sainz (2020)",
    maiorVencedor: "Max Verstappen (4 vitórias)",
    comprimento: "4.318 km",
    numVoltas: 71,
  },

  {
    race: "GP da Inglaterra",
    date: "6 de Julho",
    url: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Great_Britain_Circuit",
    primeiraEdicao: "1950",
    tempoRecorde: "1:27.097 (Max Verstappen (2020)",
    maiorVencedor: "Lewis Hamilton (8 vitórias)",
    comprimento: "5.891 km",
    numVoltas: 52,
  },

  {
    race: "GP da Bélgica",
    date: "27 de Julho",
    url: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Belgium_Circuit",
    primeiraEdicao: "1950",
    tempoRecorde: "1:44.701 (Sergio Perez (2024)",
    maiorVencedor: "Michael Schumacher (6 vitórias)",
    comprimento: "7.004 km",
    numVoltas: 44,
  },

  {
    race: "GP da Hungria",
    date: "3 de Agosto",
    url: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Hungary_Circuit",
    primeiraEdicao: "1986",
    tempoRecorde: "1:16.627 (Lewis Hamilton (2020)",
    maiorVencedor: "Lewis Hamilton (8 vitórias)",
    comprimento: "4.381 km",
    numVoltas: 70,
  },

  {
    race: "GP da Holanda",
    date: "31 de Agosto",
    url: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Netherlands_Circuit",
    primeiraEdicao: "1952",
    tempoRecorde: "1:11.097 (Lewis Hamilton (2021)",
    maiorVencedor: "Jim Clark (4 vitórias)",
    comprimento: "4.259 km",
    numVoltas: 72,
  },

  {
    race: "GP da Itália",
    date: "7 de Setembro",
    url: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Italy_Circuit",
    primeiraEdicao: "1950",
    tempoRecorde: "1:21.046 (Rubens Barrichello (2004)",
    maiorVencedor: "Michael Schumacher e Lewis Hamilton (5 vitórias)",
    comprimento: "5.793 km",
    numVoltas: 53,
  },

  {
    race: "GP do Azerbaijão",
    date: "21 de Setembro",
    url: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Baku_Circuit",
    primeiraEdicao: "2016",
    tempoRecorde: "1:43.009 (Charles Leclerc (2019)",
    maiorVencedor: "Sergio Perez (8 vitórias)",
    comprimento: "6.003 km",
    numVoltas: 51,
  },

  {
    race: "GP de Singapura",
    date: "5 de Outubro",
    url: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Singapore_Circuit",
    primeiraEdicao: "2008",
    tempoRecorde: "1:34.486 (Daniel Ricciardo (2024)",
    maiorVencedor: "Sebastian Vettel (5 vitórias)",
    comprimento: "4.940 km",
    numVoltas: 62,
  },

  {
    race: "GP dos Estados Unidos",
    date: "19 de Outubro",
    url: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/USA_Circuit",
    primeiraEdicao: "2012",
    tempoRecorde: "1:36.169 (Charles Leclerc (2019)",
    maiorVencedor: "Lewis Hamilton (6 vitórias)",
    comprimento: "5.513 km",
    numVoltas: 56,
  },

  {
    race: "GP do México",
    date: "26 de Outubro",
    url: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Mexico_Circuit",
    primeiraEdicao: "1963",
    tempoRecorde: "1:17.774 (Valtteri Bottas (2021)",
    maiorVencedor: "Max Verstappen (5 vitórias)",
    comprimento: "4.304 km",
    numVoltas: 71,
  },

  {
    race: "GP do Brasil",
    date: "9 de Novembro",
    url: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Brazil_Circuit",
    primeiraEdicao: "1973",
    tempoRecorde: "1:10.540 (Valtteri Bottas (2018)",
    maiorVencedor: "Michael Schumacher (4 vitórias)",
    comprimento: "4.309 km",
    numVoltas: 71,
  },

  {
    race: "GP de Las Vegas",
    date: "22 de Novembro",
    url: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Las_Vegas_Circuit",
    primeiraEdicao: "2023",
    tempoRecorde: "1:34.876 (Lando Norris (2024)",
    maiorVencedor: "Max Verstappen (1 vitória)",
    comprimento: "6.201 km",
    numVoltas: 50,
  },

  {
    race: "GP do Catar",
    date: "30 de Novembro",
    url: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Qatar_Circuit",
    primeiraEdicao: "2021",
    tempoRecorde: "1:22.384 (Lando Norris (2024)",
    maiorVencedor: "Max Verstappen e Lewis Hamilton (1 vitória)",
    comprimento: "5.419 km",
    numVoltas: 57,
  },

  {
    race: "GP de Abu Dhabi",
    date: "7 de Dezembro",
    url: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Abu_Dhabi_Circuit",
    primeiraEdicao: "2009",
    tempoRecorde: "1:25.637 (Kevin Magnussen (2024)",
    maiorVencedor: "Lewis Hamilton (5 vitórias)",
    comprimento: "5.281 km",
    numVoltas: 58,
  },
];
